[package]
name = "adventcode23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array_map = "0.4.0"
itertools = "0.12.0"
nom = "7.1.3"
rayon = "1.8.0"
smallvec = "1.11.2"
strum = "0.25.0"
